// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {apiGO} from '../models';
import {main} from '../models';

export function AddProxys(arg1:any):Promise<Array<utils.Proxies>>;

export function AuthAccounts(arg1:any):Promise<Array<apiGO.Info>>;

export function GetAllTasks():Promise<Array<utils.Tasks>>;

export function GetProxys():Promise<Array<string>>;

export function GetRequestData(arg1:string):Promise<string>;

export function GetTaskLogs(arg1:string):Promise<main.Logs>;

export function GetThreeChar():Promise<string>;

export function ReturnAccounts():Promise<Array<apiGO.Info>>;

export function TaskAdd(arg1:any):Promise<void>;

export function TaskDelete(arg1:any):Promise<boolean>;
