// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxys(arg1) {
  return window['go']['main']['App']['AddProxys'](arg1);
}

export function AuthAccounts(arg1) {
  return window['go']['main']['App']['AuthAccounts'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetProxys() {
  return window['go']['main']['App']['GetProxys']();
}

export function GetRequestData(arg1) {
  return window['go']['main']['App']['GetRequestData'](arg1);
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetThreeChar() {
  return window['go']['main']['App']['GetThreeChar']();
}

export function ReturnAccounts() {
  return window['go']['main']['App']['ReturnAccounts']();
}

export function TaskAdd(arg1) {
  return window['go']['main']['App']['TaskAdd'](arg1);
}

export function TaskDelete(arg1) {
  return window['go']['main']['App']['TaskDelete'](arg1);
}
